laurent_back_office:
    resource: '@LaurentBackOfficeBundle/config/routes.yaml'

spipu_user:
    resource: '@SpipuUserBundle/config/routes.yaml'

spipu_configuration:
    resource: '@SpipuConfigurationBundle/config/routes.yaml'

spipu_process:
    resource: '@SpipuProcessBundle/config/routes.yaml'
